import  os
from dotenv import load_dotenv

load_dotenv()

# Twitter keys
TWITTER_API_KEY = os.getenv("TWITTER_API_KEY")
TWITTER_API_SECRET = os.getenv("TWITTER_API_SECRET_KEY")
TWITTER_ACCESS_TOKEN = os.getenv("TWITTER_ACCESS_TOKEN")
TWITTER_ACCESS_TOKEN_SECRET = os.getenv("TWITTER_ACCESS_TOKEN_SECRET")
TWITTER_BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN")

print("TWITTER_API_KEY =", TWITTER_API_KEY)
print("TWITTER_API_SECRET =", TWITTER_API_SECRET)
print("TWITTER_ACCESS_TOKEN =", TWITTER_ACCESS_TOKEN)
print("TWITTER_ACCESS_TOKEN_SECRET =", TWITTER_ACCESS_TOKEN_SECRET)
print("TWITTER_BEARER_TOKEN =", TWITTER_BEARER_TOKEN)
